### ISSUE TITLE
Debian 10 support with tomcat9

### ISSUE THREAD

**Issue by danny-smit** [saltstack-formulas/tomcat-formula#108]
I'm using this formula for Debian 9 (tomcat8) and wanted to use it for Debian 10 as well (tomcat9),  which isn't supported by the formula yet. At first that seemed as easy as applying the correct information to the codenamemap. 

However, the map.jinja seems to merge the osmap and oscodenamemap in the reverse order (at least compared to the implementation in most formulas). 
In most formulas the map.jinja works with mapping yml files, where the more generic mappings are overruled by the more specific mappings. E.g.:
  defaults.yml -> osfamilymap.yml -> osmap.yml -> oscodenamemap.yml

Is there a good reason why this is implemented differently in this fomula's map.jinja? As it doesn't seem to work as expected.

Are there objections against changing that in a more common used?

I can create a pull request if that works.

**Comment by noelmcloughlin** [comment]
No objections, highly welcome!  Ideally, the tomcat formula follows https://github.com/saltstack-formulas/template-formula way of doing things, although anything is probably better ;-)

**Comment by danny-smit** [comment]
Thanks, I'll try to follow that template as example.

**Comment by danny-smit** [comment]
One question about the template-formula, is the 'osfinger' grain preferred over the 'oscodename'?  I haven't see 'osfinger' being used for this before.

**Comment by noelmcloughlin** [comment]
I'm not sure there is any preference.

**Comment by myii** [comment]
@danny-smit When I first started with formulas, I was more used to `oscodename` as well (see `postgres-formula`).  However, I've changed my mind since then.  `osfinger` is better supported and has generally better values (see `centos-6` => `Final`?!):

**Platform**|**oscodename**|**osfinger**
-----|-----|-----
debian-10|buster|Debian-10
debian-9|stretch|Debian-9
debian-8|jessie|Debian-8
ubuntu-18.04|bionic|Ubuntu-18.04
ubuntu-16.04|xenial|Ubuntu-16.04
centos-8|CentOS Linux 8 (Core)|CentOS Linux-8
centos-7|CentOS Linux 7 (Core)|CentOS Linux-7
centos-6|Final|CentOS-6
fedora-31|Thirty One|Fedora-31
fedora-30|Thirty|Fedora-30
fedora-29|Twenty Nine|Fedora-29
opensuse-leap-15.1|openSUSE Leap 15.1|Leap-15
amazonlinux-2|Amazon Linux 2|Amazon Linux-2
amazonlinux-1| |Amazon Linux AMI-2018
arch-base-latest|Arch Linux| 
freebsd-12.0| |FreeBSD-12
windows-81| |Windows-8.1
macos-10| |Mac OS X 10.14.6-10
gentoo-stage3|Gentoo/Linux|Gentoo-2

**Comment by danny-smit** [comment]
Thanks for the information, I applied  the suggested changes almost exactly according to the template-formula (including the osfingermap.yml). 

I tried to verify using the existing tests (hoping to extend the tests as well), but I'm having some trouble getting them to work. They seem broken already. Suggestions to fix that are welcome.

**Comment by myii** [comment]
@danny-smit Thanks for tackling that.  Don't worry about the CI, that all needs to be upgraded.  I'll try to get around to your PR over the next day or so (there's a logjam of big PRs at the moment, unfortunately).  Feel free to ping me if you don't hear from me within that time.
